/*
 * Install the Generative AI SDK
 *
 * $ npm install @google/generative-ai
 */
import { GoogleGenerativeAI } from "@google/generative-ai";
  
  const apiKey = process.env.GEMINI_API_KEY;
  const genAI = new GoogleGenerativeAI(apiKey);
  
  const model = genAI.getGenerativeModel({
    model: "gemini-1.5-flash",
  });
  
  const generationConfig = {
    temperature: 1,
    topP: 0.95,
    topK: 64,
    maxOutputTokens: 8192,
    responseMimeType: "application/json",
  };
  
  async function animationScriptGenerator(prompt) {
    const parts = [
      {text: "You are tasked with taking an initial podcast script and splitting the speech into smaller dialogue segments, while adding annotations for facial expressions, animations, and tone. Below are the detailed requirements:Input Format:The input will consist of a JSON object with a combined speech for each speaker. The structure is as follows:Speaker: The name of the speaker.Speech: The complete dialogue of the speaker.Tone: The tone of the speech, such as 'Informative', 'Casual', 'Serious', etc.Output Format:The output must be a JSON object where each speaker’s complete speech is split into smaller text segments. Each segment must include the following fields:Speaker: The name of the speaker.Speech: An array of smaller text segments from the speaker's complete speech.FaceExpression: The facial expression corresponding to the content of each segment, selected from the following list:Smile: For introductions or light-hearted content.Happy: For enthusiastic or celebratory content.Laughing: For humorous moments.Neutral: For factual or serious discussions.Curious: For asking questions or expressing interest.Surprised: For reactions to unexpected information.Animation: The animation corresponding to each segment, selected from the following list:Talking_1: For standard conversation or explanations.Talking_2: For continuing thoughts or shifts in tone.Introducing: For introductions or new topics.Explaining: For detailed information or analysis.Laughing: For humor or light-hearted moments.Tone: The tone for each segment, which should match the speech’s content. The tone should be one of the following:NeutralFriendly/WarmConfidentPersuasiveSeriousCasualExcitedCurious"},
      {text: "input: {\n  \"Script\": [\n    {\n      \"Speaker\": \"Host\",\n      \"Speech\": \"Welcome everyone to today's episode. We're diving into climate change and its impact on wildlife. I have two amazing guests with me today to discuss this. Let's get started!\",\n      \"Tone\": \"Friendly/Warm\"\n    },\n    {\n      \"Speaker\": \"Guest_1\",\n      \"Speech\": \"Climate change has already caused significant disruptions. We’ve seen ecosystems completely altered due to the warming planet.\",\n      \"Tone\": \"Serious\"\n    }\n  ]\n}"},
      {text: "output: {\n  \"Script\": [\n    {\n      \"Speaker\": \"Host\",\n      \"Speech\": [\n        {\n          \"Text\": \"Welcome everyone to today's episode.\",\n          \"FaceExpression\": \"Smile\",\n          \"Animation\": \"Introducing\",\n          \"Tone\": \"Friendly/Warm\"\n        },\n        {\n          \"Text\": \"We're diving into climate change and its impact on wildlife.\",\n          \"FaceExpression\": \"Neutral\",\n          \"Animation\": \"Talking_1\",\n          \"Tone\": \"Neutral\"\n        },\n        {\n          \"Text\": \"I have two amazing guests with me today to discuss this.\",\n          \"FaceExpression\": \"Happy\",\n          \"Animation\": \"Introducing\",\n          \"Tone\": \"Friendly/Warm\"\n        },\n        {\n          \"Text\": \"Let's get started!\",\n          \"FaceExpression\": \"Excited\",\n          \"Animation\": \"Talking_1\",\n          \"Tone\": \"Excited\"\n        }\n      ]\n    },\n    {\n      \"Speaker\": \"Guest_1\",\n      \"Speech\": [\n        {\n          \"Text\": \"Climate change has already caused significant disruptions.\",\n          \"FaceExpression\": \"Neutral\",\n          \"Animation\": \"Explaining\",\n          \"Tone\": \"Serious\"\n        },\n        {\n          \"Text\": \"We’ve seen ecosystems completely altered due to the warming planet.\",\n          \"FaceExpression\": \"Neutral\",\n          \"Animation\": \"Talking_2\",\n          \"Tone\": \"Serious\"\n        }\n      ]\n    }\n  ]\n}"},
      {text: "input: {\n  \"Script\": [\n    {\n      \"Speaker\": \"Host\",\n      \"Speech\": \"Welcome to our podcast! Today, we're talking about the latest in space exploration. Joining me is Dr. Lisa, an expert in space science. Dr. Lisa, tell us what new missions NASA is working on?\",\n      \"Tone\": \"Friendly/Warm\"\n    },\n    {\n      \"Speaker\": \"Guest_1\",\n      \"Speech\": \"Thank you! NASA is currently focused on returning humans to the Moon. This is part of the Artemis program, which aims to establish a sustainable presence on the Moon.\",\n      \"Tone\": \"Neutral\"\n    }\n  ]\n}"},
      {text: "output: {\n  \"Script\": [\n    {\n      \"Speaker\": \"Host\",\n      \"Speech\": [\n        {\n          \"Text\": \"Welcome to our podcast!\",\n          \"FaceExpression\": \"Smile\",\n          \"Animation\": \"Introducing\",\n          \"Tone\": \"Friendly/Warm\"\n        },\n        {\n          \"Text\": \"Today, we're talking about the latest in space exploration.\",\n          \"FaceExpression\": \"Curious\",\n          \"Animation\": \"Talking_1\",\n          \"Tone\": \"Curious\"\n        },\n        {\n          \"Text\": \"Joining me is Dr. Lisa, an expert in space science.\",\n          \"FaceExpression\": \"Happy\",\n          \"Animation\": \"Introducing\",\n          \"Tone\": \"Friendly/Warm\"\n        },\n        {\n          \"Text\": \"Dr. Lisa, tell us what new missions NASA is working on?\",\n          \"FaceExpression\": \"Curious\",\n          \"Animation\": \"Talking_2\",\n          \"Tone\": \"Curious\"\n        }\n      ]\n    },\n    {\n      \"Speaker\": \"Guest_1\",\n      \"Speech\": [\n        {\n          \"Text\": \"Thank you!\",\n          \"FaceExpression\": \"Happy\",\n          \"Animation\": \"Talking_1\",\n          \"Tone\": \"Friendly/Warm\"\n        },\n        {\n          \"Text\": \"NASA is currently focused on returning humans to the Moon.\",\n          \"FaceExpression\": \"Neutral\",\n          \"Animation\": \"Explaining\",\n          \"Tone\": \"Neutral\"\n        },\n        {\n          \"Text\": \"This is part of the Artemis program, which aims to establish a sustainable presence on the Moon.\",\n          \"FaceExpression\": \"Neutral\",\n          \"Animation\": \"Talking_2\",\n          \"Tone\": \"Neutral\"\n        }\n      ]\n    }\n  ]\n}"},
      {text: "input: {\n  \"Script\": [\n    {\n      \"Speaker\": \"Host\",\n      \"Speech\": \"Welcome back! In this episode, we'll be talking about fitness tips for beginners. I'm joined by John, a fitness trainer.\",\n      \"Tone\": \"Casual\"\n    },\n    {\n      \"Speaker\": \"Guest_1\",\n      \"Speech\": \"Thanks for having me. It's important for beginners to focus on consistency and building good habits rather than trying to do everything at once.\",\n      \"Tone\": \"Neutral\"\n    }\n  ]\n}"},
      {text: "output: {\n  \"Script\": [\n    {\n      \"Speaker\": \"Host\",\n      \"Speech\": [\n        {\n          \"Text\": \"Welcome back!\",\n          \"FaceExpression\": \"Smile\",\n          \"Animation\": \"Introducing\",\n          \"Tone\": \"Friendly/Warm\"\n        },\n        {\n          \"Text\": \"In this episode, we'll be talking about fitness tips for beginners.\",\n          \"FaceExpression\": \"Neutral\",\n          \"Animation\": \"Talking_1\",\n          \"Tone\": \"Casual\"\n        },\n        {\n          \"Text\": \"I'm joined by John, a fitness trainer.\",\n          \"FaceExpression\": \"Happy\",\n          \"Animation\": \"Introducing\",\n          \"Tone\": \"Casual\"\n        }\n      ]\n    },\n    {\n      \"Speaker\": \"Guest_1\",\n      \"Speech\": [\n        {\n          \"Text\": \"Thanks for having me.\",\n          \"FaceExpression\": \"Happy\",\n          \"Animation\": \"Talking_1\",\n          \"Tone\": \"Friendly/Warm\"\n        },\n        {\n          \"Text\": \"It's important for beginners to focus on consistency\",\n          \"FaceExpression\": \"Neutral\",\n          \"Animation\": \"Explaining\",\n          \"Tone\": \"Neutral\"\n        },\n        {\n          \"Text\": \"and building good habits rather than trying to do everything at once.\",\n          \"FaceExpression\": \"Serious\",\n          \"Animation\": \"Talking_2\",\n          \"Tone\": \"Neutral\"\n        }\n      ]\n    }\n  ]\n}"},
      {text: "input: {\n  \"Script\": [\n    {\n      \"Speaker\": \"Host\",\n      \"Speech\": \"Hi everyone! On today’s show, we’ll dive into the world of blockchain technology. Our guest is Michael, an expert in the field.\",\n      \"Tone\": \"Confident\"\n    },\n    {\n      \"Speaker\": \"Guest_1\",\n      \"Speech\": \"Hello! Blockchain has really evolved, and it's about much more than just cryptocurrencies.\",\n      \"Tone\": \"Excited\"\n    }\n  ]\n}"},
      {text: "output: {\n  \"Script\": [\n    {\n      \"Speaker\": \"Host\",\n      \"Speech\": [\n        {\n          \"Text\": \"Hi everyone!\",\n          \"FaceExpression\": \"Smile\",\n          \"Animation\": \"Introducing\",\n          \"Tone\": \"Friendly/Warm\"\n        },\n        {\n          \"Text\": \"On today’s show, we’ll dive into the world of blockchain technology.\",\n          \"FaceExpression\": \"Curious\",\n          \"Animation\": \"Talking_1\",\n          \"Tone\": \"Confident\"\n        },\n        {\n          \"Text\": \"Our guest is Michael, an expert in the field.\",\n          \"FaceExpression\": \"Happy\",\n          \"Animation\": \"Introducing\",\n          \"Tone\": \"Confident\"\n        }\n      ]\n    },\n    {\n      \"Speaker\": \"Guest_1\",\n      \"Speech\": [\n        {\n          \"Text\": \"Hello!\",\n          \"FaceExpression\": \"Happy\",\n          \"Animation\": \"Talking_1\",\n          \"Tone\": \"Excited\"\n        },\n        {\n          \"Text\": \"Blockchain has really evolved, and it's about much more than just cryptocurrencies.\",\n          \"FaceExpression\": \"Curious\",\n          \"Animation\": \"Explaining\",\n          \"Tone\": \"Excited\"\n        }\n      ]\n    }\n  ]\n}"},
      {text: `input: ${JSON.stringify(prompt)}`},
      {text: "output: "},
    ];
  
    const result = await model.generateContent({
      contents: [{ role: "user", parts }],
      generationConfig,
    });
    //console.log(result.response.text());
    return result.response.text();
  }
  
 export default animationScriptGenerator;